server {
    listen 80;
    
    # Serve static files
    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        # Fallback for React Router
        try_files $uri $uri/ /index.html;
    }
}
